
export function countries(){
  return ['afghanistan', 'albania', 'algeria', 'american_samoa', 
  'andorra', 'angola', 'anguilla', 'antigua_and_barbuda', 'argentina', 'armenia', 'aruba', 'australia',  'austria', 'azerbaijan', 'bahamas', 'bahrain', 'bangladesh', 'barbados', 'belarus', 'belgium', 'belize', 'benin', 'bermuda', 'bhutan', 'bolivia__plurinational_state_of_', 'bonaire__sint_eustatius_and_saba', 'bosnia_and_herzegovina', 'botswana', 'brazil', 'british_virgin_islands', 'brunei_darussalam', 'bulgaria', 'burkina_faso', 'burundi', 'cabo_verde', 'cambodia', 'cameroon', 'canada', 'caribbean', 'cayman_islands', 'central_african_republic',  'chad', 'chile', 'china', 'china__hong_kong_sar', 'china__macao_sar', 'china__taiwan_province_of_china', 'colombia', 'comoros', 'congo', 'cook_islands', 'costa_rica', 'cote_d_ivoire', 'croatia', 'cuba', 'curacao', 'cyprus', 'czechia', 'dem__people_s_republic_of_korea', 'democratic_republic_of_the_congo', 'denmark', 'djibouti', 'dominica', 'dominican_republic', 'ecuador', 'egypt', 'el_salvador', 'equatorial_guinea', 'eritrea', 'estonia', 'eswatini', 'ethiopia',  'falkland_islands__malvinas_', 'faroe_islands', 'fiji', 'finland', 'france', 'french_guiana', 'french_polynesia', 'gabon', 'gambia', 'georgia', 'germany', 'ghana', 'gibraltar', 'greece', 'greenland', 'grenada', 'guadeloupe', 'guam', 'guatemala', 'guernsey', 'guinea', 'guinea_bissau', 'guyana', 'haiti', 'honduras', 'hungary', 'iceland', 'india', 'indonesia', 'iran__islamic_republic_of_', 'iraq', 'ireland', 'isle_of_man', 'israel', 'italy', 'jamaica', 'japan', 'jersey', 'jordan', 'kazakhstan', 'kenya', 'kiribati', 
  'kosovo__under_unsc_res__1244_', 'kuwait', 'kyrgyzstan', 'lao_people_s_democratic_republic', 'latvia', 'lebanon', 'lesotho', 'liberia', 'libya', 'liechtenstein', 'lithuania', 'luxembourg', 'madagascar', 'malawi', 'malaysia', 'maldives', 'mali', 'malta', 'marshall_islands', 'martinique', 'mauritania', 'mauritius', 'mayotte', 'melanesia', 'mexico', 'micronesia', 'micronesia__fed__states_of_', 'monaco', 'mongolia', 'montenegro', 'montserrat', 'morocco', 'mozambique', 'myanmar', 'namibia', 'nauru', 'nepal', 'netherlands', 'new_caledonia', 'new_zealand', 'nicaragua', 'niger', 'nigeria', 'niue', 'north_macedonia',  'northern_mariana_islands', 'norway',   'oman', 'pakistan', 'palau', 'panama', 'papua_new_guinea', 'paraguay', 'peru', 'philippines', 'poland', 'polynesia', 'portugal', 'puerto_rico', 'qatar', 'republic_of_korea', 'republic_of_moldova', 'reunion', 'romania', 'russian_federation', 'rwanda', 'saint_barthelemy', 'saint_helena', 'saint_kitts_and_nevis', 'saint_lucia', 'saint_martin__french_part_', 'saint_pierre_and_miquelon', 'saint_vincent_and_the_grenadines', 'samoa', 'san_marino', 'sao_tome_and_principe', 'saudi_arabia', 'senegal', 'serbia', 'seychelles', 'sierra_leone', 'singapore', 'sint_maarten__dutch_part_', 'slovakia', 'slovenia', 'solomon_islands', 'somalia', 'south_africa', 'south_sudan', 'spain', 'sri_lanka', 'state_of_palestine', 'sudan', 'suriname', 'sweden', 'switzerland', 'syrian_arab_republic', 'tajikistan', 'thailand', 'timor_leste', 'togo', 'tokelau', 'tonga', 'trinidad_and_tobago', 'tunisia', 'turkiye', 'turkmenistan', 'turks_and_caicos_islands', 'tuvalu', 'uganda', 'ukraine', 'united_arab_emirates', 'united_kingdom', 'united_republic_of_tanzania', 'united_states_of_america', 'united_states_virgin_islands', 'uruguay', 'uzbekistan', 'vanuatu', 'venezuela__bolivarian_republic_of_', 'viet_nam', 'wallis_and_futuna_islands',  'yemen', 'zambia', 'zimbabwe'] 
}

export function Regionals(){
  return  {
    "":['Abc Order'],
    "Africa": ["Northern Africa", "Eastern Africa", "Middle Africa", "Southern Africa", "Western Africa"],
    "Africa": ["Northern Africa", "Eastern Africa", "Middle Africa", "Southern Africa", "Western Africa"],
    "Americas": ["Caribbean", "Central America", "South America", "Northern America"],
    "Asia": ["Central Asia", "Eastern Asia", "Southern Asia", "South Eastern Asia", "Western Asia"],
    "Europe": ["Eastern Europe", "Northern Europe", "Southern Europe", "Western Europe"],
    "Oceania": ["Australia and New Zealand", "Melanesia", "Micronesia", "Polynesia"],
    "-":['World', 'Region','Develop','Income']};
  }

export function worlds(){
  return ['world']
}
export function regions(){
  return ['sub_saharan_africa', 'asia','northern_africa_and_western_asia','central_and_southern_asia','eastern_and_south_eastern_asia','latin_america_and_the_caribbean', 'oceania__excluding_australia_and_new_zealand_','australia_new_zealand','europe_and_northern_america' ,'africa', 'eastern_africa',
  'eastern_asia', 'central_america',  'central_asia', 'south_america', 'south_eastern_asia', 'southern_africa', 'southern_asia', 
  'northern_europe', 'southern_europe', 'western_africa', 'western_asia', 'western_europe', 'western_sahara','europe', 'europe_and_northern_america',  'eastern_europe','northern_africa','northern_america', 'oceania' ]
}
export function develops(){
  return ['more_developed_regions', 'less_developed_regions', 'least_developed_countries','less_developed_regions__excluding_least_developed_countries', 'less_developed_regions__excluding_china', 'land_locked_developing_countries__lldc_', 'small_island_developing_states__sids_']
}
export function incomes(){
  return ['high_income_countries', 'middle_income_countries', 'upper_middle_income_countries', 'lower_middle_income_countries', 'low_income_countries',  'no_income_group_available' ]
}

export function RegionsCountries(){
  return { "Northern Africa": ['algeria', 'egypt', 'libya', 'morocco', 'sudan', 'tunisia', 'western_sahara'],
  "Eastern Africa": ['burundi', 'comoros', 'djibouti', 'eritrea', 'ethiopia', 'kenya', 'madagascar', 'malawi', 'mauritius', 'mayotte', 'mozambique', 'reunion', 'rwanda', 'seychelles', 'somalia', 'south_sudan', 'uganda', 'united_republic_of_tanzania', 'zambia', 'zimbabwe'],
  "Middle Africa": ['angola', 'cameroon', 'central_african_republic', 'chad', 'congo', 'democratic_republic_of_the_congo', 'equatorial_guinea', 'gabon', 'sao_tome_and_principe'],
  "Southern Africa": ['botswana', 'eswatini', 'lesotho', 'namibia', 'south_africa'],
  "Western Africa": ['benin', 'burkina_faso', 'cabo_verde', 'cote_d_ivoire', 'gambia', 'ghana', 'guinea', 'guinea_bissau', 'liberia', 'mali', 'mauritania', 'niger', 'nigeria', 'senegal', 'sierra_leone', 'togo'],
  "Caribbean": ['anguilla', 'antigua_and_barbuda', 'aruba', 'bahamas', 'barbados', 'bonaire_sint eustatius_and_saba', 'british_virgin_islands', 'cayman_islands', 'cuba', 'curacao', 'dominica', 'dominican_republic', 'grenada', 'guadeloupe', 'haiti', 'jamaica', 'martinique', 'montserrat', 'puerto_rico', 'saint_barthelemy', 'saint_kitts_and_nevis', 'saint_lucia', 'saint_martin_french part', 'saint_vincent_and_the_grenadines', 'sint_maarten__dutch_part_', 'trinidad_and_tobago', 'turks_and_caicos_islands', 'united_states_virgin_islands'],
  "Central America": ['belize', 'costa_rica', 'el_salvador', 'guatemala', 'honduras', 'mexico', 'nicaragua', 'panama'],
  "South America": ['argentina', 'bolivia__plurinational_state_of_', 'brazil', 'chile', 'colombia', 'ecuador', 'falkland_islands_malvinas', 'french_guiana', 'guyana', 'paraguay', 'peru', 'suriname', 'uruguay', 'venezuela__bolivarian_republic_of_'],
  "Northern America": ['bermuda', 'canada', 'greenland', 'united_states_of_america'],
  "Central Asia": ['kazakhstan', 'kyrgyzstan', 'tajikistan', 'turkmenistan', 'uzbekistan'],
  "Eastern Asia": ['china', 'china__hong_kong_sar', 'china__macao_sar', 'china__taiwan_province_of_china', 'dem_people_s_republic_of_korea', 'japan', 'mongolia', 'republic_of_korea'],
  "Southern Asia": ['afghanistan', 'bangladesh', 'bhutan', 'india', 'iran islamic republic of', 'maldives', 'nepal', 'pakistan', 'sri_lanka'],
  "South Eastern Asia": ['brunei_darussalam', 'cambodia', 'indonesia', 'lao_people_s_democratic_republic', 'malaysia', 'myanmar', 'philippines', 'singapore', 'thailand', 'timor_leste', 'viet_nam'],
  "Western Asia": ['armenia', 'azerbaijan', 'bahrain', 'cyprus', 'georgia', 'iraq', 'israel', 'jordan', 'kuwait', 'lebanon', 'oman', 'qatar', 'saudi_arabia', 'state_of_palestine', 'syrian arab_republic', 'turkey', 'united_arab_emirates', 'yemen'],
  "Eastern Europe": ['belarus', 'bulgaria', 'czechia', 'hungary', 'poland', 'republic_of_moldova', 'romania', 'russian_federation', 'slovakia', 'ukraine'],
  "Northern Europe": ['denmark', 'estonia', 'faroe_islands', 'finland', 'iceland', 'ireland', 'isle_of_man', 'latvia', 'lithuania', 'norway', 'sweden', 'united_kingdom'],
  "Southern Europe": ['albania', 'andorra', 'bosnia_and_herzegovina', 'croatia', 'gibraltar', 'greece', 'holy_see', 'italy', 'kosovo__under_unsc_res__1244_', 'malta', 'montenegro', 'north macedonia', 'portugal', 'san_marino', 'serbia', 'slovenia', 'spain'],
  "Western Europe": ['austria', 'belgium', 'france', 'germany', 'liechtenstein', 'luxembourg', 'monaco', 'netherlands', 'switzerland'],
  "Australia and New Zealand": ['australia', 'new_zealand'],
  "Melanesia": ['fiji', 'new_caledonia', 'papua_new_guinea', 'solomon_islands', 'vanuatu'],
  "Micronesia": ['guam', 'kiribati', 'marshall_islands', 'micronesia__fed__states_of_', 'nauru', 'northern_mariana_islands', 'palau'],
  "Polynesia": ['american_samoa', 'cook_islands', 'french_polynesia', 'niue', 'samoa', 'tokelau', 'tonga', 'tuvalu', 'wallis_and_futuna_islands']}
};

const original_data = ['afghanistan', 'africa', 'albania', 'algeria', 'american_samoa', 
'andorra', 'angola', 'anguilla', 'antigua_and_barbuda', 'argentina', 'armenia', 'aruba', 'asia', 'australia', 'australia_new_zealand', 'austria', 'azerbaijan', 'bahamas', 'bahrain', 'bangladesh', 'barbados', 'belarus', 'belgium', 'belize', 'benin', 'bermuda', 'bhutan', 'bolivia__plurinational_state_of_', 'bonaire__sint_eustatius_and_saba', 'bosnia_and_herzegovina', 'botswana', 'brazil', 'british_virgin_islands', 'brunei_darussalam', 'bulgaria', 'burkina_faso', 'burundi', 'cabo_verde', 'cambodia', 'cameroon', 'canada', 'caribbean', 'cayman_islands', 'central_african_republic', 'central_america', 'central_and_southern_asia', 'central_asia', 'chad', 'chile', 'china', 'china__hong_kong_sar', 'china__macao_sar', 'china__taiwan_province_of_china', 'colombia', 'comoros', 'congo', 'cook_islands', 'costa_rica', 'cote_d_ivoire', 'croatia', 'cuba', 'curacao', 'cyprus', 'czechia', 'dem__people_s_republic_of_korea', 'democratic_republic_of_the_congo', 'denmark', 'djibouti', 'dominica', 'dominican_republic', 'eastern_africa', 'eastern_and_south_eastern_asia', 'eastern_asia', 'eastern_europe', 'ecuador', 'egypt', 'el_salvador', 'equatorial_guinea', 'eritrea', 'estonia', 'eswatini', 'ethiopia', 'europe', 'europe_and_northern_america', 'falkland_islands__malvinas_', 'faroe_islands', 'fiji', 'finland', 'france', 'french_guiana', 'french_polynesia', 'gabon', 'gambia', 'georgia', 'germany', 'ghana', 'gibraltar', 'greece', 'greenland', 'grenada', 'guadeloupe', 'guam', 'guatemala', 'guernsey', 'guinea', 'guinea_bissau', 'guyana', 'haiti', 'high_income_countries', 'honduras', 'hungary', 'iceland', 'india', 'indonesia', 'iran__islamic_republic_of_', 'iraq', 'ireland', 'isle_of_man', 'israel', 'italy', 'jamaica', 'japan', 'jersey', 'jordan', 'kazakhstan', 'kenya', 'kiribati', 
'kosovo__under_unsc_res__1244_', 'kuwait', 'kyrgyzstan', 'land_locked_developing_countries__lldc_', 'lao_people_s_democratic_republic', 'latin_america_and_the_caribbean', 'latvia', 'least_developed_countries', 'lebanon', 'lesotho', 'less_developed_regions', 'less_developed_regions__excluding_china', 'less_developed_regions__excluding_least_developed_countries', 'liberia', 'libya', 'liechtenstein', 'lithuania', 'low_income_countries', 'lower_middle_income_countries', 'luxembourg', 'madagascar', 'malawi', 'malaysia', 'maldives', 'mali', 'malta', 'marshall_islands', 'martinique', 'mauritania', 'mauritius', 'mayotte', 'melanesia', 'mexico', 'micronesia', 'micronesia__fed__states_of_', 'middle_africa', 'middle_income_countries', 'monaco', 'mongolia', 'montenegro', 'montserrat', 'more_developed_regions', 'morocco', 'mozambique', 'myanmar', 'namibia', 'nauru', 'nepal', 'netherlands', 'new_caledonia', 'new_zealand', 'nicaragua', 'niger', 'nigeria', 'niue', 'no_income_group_available', 'north_macedonia', 'northern_africa', 'northern_africa_and_western_asia', 'northern_america', 'northern_europe', 'northern_mariana_islands', 'norway', 'oceania', 'oceania__excluding_australia_and_new_zealand_', 'oman', 'pakistan', 'palau', 'panama', 'papua_new_guinea', 'paraguay', 'peru', 'philippines', 'poland', 'polynesia', 
'portugal', 'puerto_rico', 'qatar', 'republic_of_korea', 'republic_of_moldova', 'reunion', 'romania', 'russian_federation', 'rwanda', 'saint_barthelemy', 'saint_helena', 'saint_kitts_and_nevis', 'saint_lucia', 'saint_martin__french_part_', 'saint_pierre_and_miquelon', 'saint_vincent_and_the_grenadines', 'samoa', 'san_marino', 'sao_tome_and_principe', 'saudi_arabia', 'senegal', 'serbia', 'seychelles', 'sierra_leone', 'singapore', 'sint_maarten__dutch_part_', 'slovakia', 'slovenia', 'small_island_developing_states__sids_', 'solomon_islands', 'somalia', 'south_africa', 'south_america', 'south_eastern_asia', 'south_sudan', 'southern_africa', 'southern_asia', 'southern_europe', 'spain', 'sri_lanka', 'state_of_palestine', 'sub_saharan_africa', 'sudan', 'suriname', 'sweden', 'switzerland', 'syrian_arab_republic', 'tajikistan', 'thailand', 'timor_leste', 'togo', 'tokelau', 'tonga', 'trinidad_and_tobago', 'tunisia', 'turkiye', 'turkmenistan', 'turks_and_caicos_islands', 'tuvalu', 'uganda', 'ukraine', 'united_arab_emirates', 'united_kingdom', 'united_republic_of_tanzania', 'united_states_of_america', 'united_states_virgin_islands', 'upper_middle_income_countries', 'uruguay', 'uzbekistan', 'vanuatu', 'venezuela__bolivarian_republic_of_', 'viet_nam', 'wallis_and_futuna_islands', 'western_africa', 'western_asia', 'western_europe', 'western_sahara', 'world', 'yemen', 'zambia', 'zimbabwe'] 


 [{"location": "Japan", "year": "1950", "age": "0-4", "male": 5758215, "female": 5548846, "total": 11307061}, {"location": "Japan", "year": "1950", "age": "5-9", "male": 4887281, "female": 4792932, "total": 9680213}, {"location": "Japan", "year": "1950", "age": "10-14", "male": 4441300, "female": 4378245, "total": 8819546}, {"location": "Japan", "year": "1950", "age": "15-19", "male": 4392687, "female": 4348039, "total": 8740726}, {"location": "Japan", "year": "1950", "age": "20-24", "male": 3949444, "female": 3987421, "total": 7936865}, {"location": "Japan", "year": "1950", "age": "25-29", "male": 2892656, "female": 3427644, "total": 6320300}, {"location": "Japan", "year": "1950", "age": "30-34", "male": 2405742, "female": 2849290, "total": 5255032}, {"location": "Japan", "year": "1950", "age": "35-39", "male": 2421441, "female": 2693655, "total": 5115096}, {"location": "Japan", "year": "1950", "age": "40-44", "male": 2223210, "female": 2296114, "total": 4519324}, {"location": "Japan", "year": "1950", "age": "45-49", "male": 2025610, "female": 1988198, "total": 4013807}, {"location": "Japan", "year": "1950", "age": "50-54", "male": 1718803, "female": 1682850, "total": 3401653}, {"location": "Japan", "year": "1950", "age": "55-59", "male": 1375121, "female": 1385596, "total": 2760717}, {"location": "Japan", "year": "1950", "age": "60-64", "male": 1103822, "female": 1206991, "total": 2310813}, {"location": "Japan", "year": "1950", "age": "65-69", "male": 779482, "female": 975823, "total": 1755305}, {"location": "Japan", "year": "1950", "age": "70-74", "male": 496405, "female": 693602, "total": 1190007}, {"location": "Japan", "year": "1950", "age": "75-79", "male": 275796, "female": 426245, "total": 702042}, {"location": "Japan", "year": "1950", "age": "80-84", "male": 120478, "female": 211910, "total": 332388}, {"location": "Japan", "year": "1950", "age": "85-89", "male": 36053, "female": 74697, "total": 110750}, {"location": "Japan", "year": "1950", "age": "90-94", "male": 6322, "female": 16379, "total": 22702}, {"location": "Japan", "year": "1950", "age": "95-99", "male": 549, "female": 1982, "total": 2531}, {"location": "Japan", "year": "1950", "age": "100+", "male": 24, "female": 126, "total": 150}]
